plugins:
  orbithy_notify_enabled:
    default: false
  orbithy_notify_api_url:
    default: 'http://localhost:8080'
  orbithy_notify_app_id:
    default: ''
    client: true
  orbithy_notify_app_secret:
    default: ''
    secret: true
  orbithy_notify_push_category:
    default: 'MARKETING'
